---
- name: download docker installation script
  sudo: yes
  shell: wget -O /etc/docker.sh https://get.docker.com/

- name: chmod docker.sh
  sudo: yes
  file: path=/etc/docker.sh mode=0744

- name: install docker
  sudo: yes
  shell: /etc/docker.sh

- name: remove docker installation script
  sudo: yes
  file: path=/etc/docker.sh state=absent
